### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by chorseng** [chijames/Poly-Encoder#1]
Dear @chijames ,

I came across your Poly-Encoder and would like to adapt it for some work purposes. I was told that I can't use it unless it is open-source licensed. I was wondering if you are willing to allow for that, perhaps through an MIT license etc.? 

https://choosealicense.com/licenses/mit/

Hope to hear from you and thank you very much!

Best Regards,
Chor Seng

**Comment by chijames** [comment]
Added.

**Comment by chorseng** [comment]
Thank you so much!
