### ISSUE TITLE
Config file missing

### ISSUE THREAD

**Issue by lkoll** [chijames/Poly-Encoder#12]
There doesn’t seem to be the config file you used to run this code, I’m just curious what some of the values you are using are. Specifically hidden size referenced in the poly encoder section to calculate your m.

**Comment by lydhr** [comment]
Please refer to [README](https://github.com/chijames/Poly-Encoder#bert-model-setup) to setup BERT model. The hidden size can be found in the bert_config.json, which is included in the model zip file you download.
