### ISSUE TITLE
这个地方为啥取的是第一个词位置的向量？

### ISSUE THREAD

**Issue by nwy2010** [chijames/Poly-Encoder#5]
https://github.com/chijames/Poly-Encoder/blob/6f0d9c4e36ac73b7547e6e88681fbb514dc10c5a/encoder.py#L20-L27
一个句子经过bert之后得到整个句子的向量表示，这个地方为啥取的是第一个词位置的向量：[0][:,0,:]

**Comment by chijames** [comment]
Then what do you want to do for all the token representations? Check section 4.2 of the original paper "We use the first output of the transformer in our experiments as it gives slightly better results."
