### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by PeterGriffinJin** [chijames/Poly-Encoder#6]
Hi! Thanks a lot for sharing your code! 
I got some question about the performance.
You propose the performance of your code on DSTC7 with bi-encoder as follows,
![image](https://user-images.githubusercontent.com/48234654/97650745-63198c00-1a95-11eb-8490-51caac59f7f4.png)

However, in the original paper, the performance of bi-encoder on DSTC7 is 
![image](https://user-images.githubusercontent.com/48234654/97650842-a83dbe00-1a95-11eb-8b54-a2ddbf041e20.png)

With your code we can get R@1 for 0.437 but the performance in the original paper is 0.565 on dev set and 0.668 on test set. I read your code carefully but find little difference with the setting in the original paper. I also change your default one-bert to two different bert for bi-encoder, but still cannot get the same performance as that in the original paper. Why?

**Comment by PeterGriffinJin** [comment]
Also in your encoder.py, when calculating the forwarding loss for bi-encoder and poly-encoder, you use the function as follows,
![image](https://user-images.githubusercontent.com/48234654/97651384-d4a60a00-1a96-11eb-99b8-009ba12d081c.png)
However, by doing so, we will ignore all negative samples and only take positive sample into consideration, which is a problem.

So maybe we should change the loss to like this?
![image](https://user-images.githubusercontent.com/48234654/97651461-15058800-1a97-11eb-881b-013fb8872235.png)

**Comment by PeterGriffinJin** [comment]
Also do you know where can we find the official code and official processed dataset for this paper?

**Comment by chijames** [comment]
1. Please check the readme again, I clearly stated the difference. (mostly because I use a smaller bert model and batch size)
2. We are calculating the cross entropy loss here, you should check the math of it. In fact, it can be reduced to this form as all candidates have label 0 except the correct answer (with label 1).
3. You can check the ParlAI github repo.

**Comment by PeterGriffinJin** [comment]
Hi, thanks for your answer.
I have tried using bert-based model here with two different bert for bi-encoder on DSTC7 dataset but still cannot get similar performance with the paper. Is this caused by batch size? I'm confused. Thanks!

**Comment by PeterGriffinJin** [comment]
Thanks for your answer!

**Comment by chijames** [comment]
BTW, I think the major difference would be the dataset used. In their original paper, they used the augmented dataset (check my readme for details).
You can refer to the last row of my table (da + bert base), where I used a larger bert model and the same augmented dataset as theirs. The numbers are pretty close I think.
