### ISSUE TITLE
Why not direct use Huggingface-BERT Pretrained Weights ?

### ISSUE THREAD

**Issue by Doragd** [chijames/Poly-Encoder#8]
Why do you convert the google-bert weight instead of directly using the bert weight of huggingface. Is there any performance difference between the two？
```python
# converted weight from google-bert
bert = BertModelClass.from_pretrained(args.bert_model, state_dict=model_state_dict) 

# huggingface weight
bert = BertModelClass.from_pretrained('bert-base-uncased') 
```

**Comment by chijames** [comment]
It's because I followed another repo (see readme) in the beginning of development. I believe you can use either one, there shouldn't be any difference.
